# Minecraft Launcher
windowrulev2 = pseudo, class:^(Minecraft Launcher)$
# Floating
windowrulev2 = float, title:Play Timer
windowrulev2 = float, class:play-timer

# Opacity
windowrule = opacity 0.85 0.75 ,class:^(kitty)$

