-- Generated by hyprconf2lua v1.3.2
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- source = ~/.config/hypr/monitors.conf -> requires manual conversion
local monitors = require("monitors")
-- TODO: convert ~/.config/hypr/monitors.conf to .lua and use require()

-- Set programs that you use

terminal = "kitty"

fileManager = "thunar"

menu = "wofi --show drun"

browser = "brave"






-- for GTK4 apps


-- for GTK3 apps

hl.config({
    misc = {
        force_default_wallpaper = 0,
        disable_hyprland_logo = true,
        initial_workspace_tracking = 1,
    },
})

--############################

--## ENVIRONMENT VARIABLES ###

--############################

hl.env("XCURSOR_SIZE", 24)

hl.env("HYPRCURSOR_SIZE", 24)

hl.env("LIBVA_DRIVER_NAME", "nvidia")

hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")

hl.env("NVD_BACKEND", "direct")

hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")

-- for Qt apps# Theme
local keybinds = require("keybinds")
local input = require("input")
local applications = require("applications")
local decorations = require("decoration")
local workspaces = require("workspaces")

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("/usr/lib/xdg-desktop-portal-hyprland &")
    hl.exec_cmd("/usr/lib/xdg-desktop-portal &")
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("nextcloud")
    hl.exec_cmd("waybar")
    hl.exec_cmd("hyprctl setcursor breeze 24")
end)

-- Exec (run every reload)
hl.on("config.reloaded", function()
    hl.exec_cmd("gsettings set org.gnome.desktop.interface color-scheme prefer-dark")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-dark")
end)
