-- Generated by hyprconf2lua v1.3.2
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- TODO: manual review: splash = false

-- TODO: manual review: preload = "~/.wallpapers/liminal.png"

-- TODO: manual review: wallpaper = "DP-1", "~/.wallpapers/liminal.png"

-- TODO: manual review: wallpaper = "DP-3", "~/.wallpapers/liminal.png"
