input {
    kb_layout = ie
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1
    accel_profile = flat
    force_no_accel=2

    sensitivity = 1

    touchpad {
        natural_scroll = true
	scroll_factor = 0.2
    }
}

device {
    name = logitech-usb-receiver
    sensitivity = 0
}

gesture = 3, horizontal, workspace
gesture = 3, down, fullscreen
