bind = SUPER CTRL, left, swapwindow, l
bind = SUPER CTRL, right, swapwindow, r
bind = SUPER SHIFT, F, fullscreen
bind = SUPER CTRL, F, fullscreen, 1
bind = SUPER, Q, killactive
bind = ALT, TAB, cyclenext

bind = SUPER, D, exec, $menu
bind = SUPER, B, exec, firefox
bind = SUPER SHIFT, S, exec, grim -g "$(slurp)" - | wl-copy
